version: 0.2

env:
  variables:
    DOMAIN: "nextwork"
    DOMAIN_OWNER: "891377087712"
    REPOSITORY: "laxmigroups-cicd"
    REGION: "ap-south-1"

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing AWS CLI...
      - aws --version

  build:
    commands:
      - echo Logging into CodeArtifact...
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
          --domain $DOMAIN \
          --domain-owner $DOMAIN_OWNER \
          --region $REGION \
          --query authorizationToken --output text)
      - echo Build started on `date`
      - mvn -s settings.xml compile
      - mvn -s settings.xml package

artifacts:
  files:
    - target/*.war
  discard-paths: no
